use_frameworks!

platform :ios, '11.0'

target 'SwiftExtensions_Example' do
  
  pod 'SwiftExtensions', :path => '../'
  
  target 'SwiftExtensions_Tests' do
    inherit! :search_paths

    
  end
end
